language: minimal
services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.25.1
    # TWINE_TEST_PASSWORD
    - secure: kr/xG5/vgqdnprA3APrcrqJcKy9cvsj1oacsfpNvf8Z40V36iX+LJTARNsFuhGBvHtMwpoHgO3zQ1uq5JCHelo55oDAKKAAeko+AhZy7tSI/G4r7ci+3njW4Tog+lfxF2JH6zSc7kUnQZj5lbDQY663uyEa3Yg7jdDcPRob+VJPQR6q3MHOzQPBmSSaR0wwIseSH+c1ETKoKD1P9eS0uhgzj9ga81Qb0U+rHRSYRxbBim15R26OkcQ9Q3TXVHL4y58ywW0E+DI9mi1UrRqmixmWHkmF9gcHlqjVOzNGqB8lHpVfaZpYvTyAf6F/LSwKW379sSv+N4Y8CLqGHjzv2qw6ivKYrOexVCFEuqIbTV7mLjEepBRyHTh/XOgugsVlpe6e8PLsf0WkCxxrYQ3Rp6n/a+V9o212B5rE31RNOY78iP4lX6qkq5W4UJGRd75pIowtfJgMFc3eNDBhXE3FcR6dWS1gGnhHzYDwpZNnnn7aETOZpu98u8XSKOMQ5AuqNuQ+KGXqiZPif/qSKtooaOUBAF0NM8tQr9VuKgYH49H73D6nQkwnAJ4EaInNF//R0rWZ/txugYNjAOXcIkWqSdGIAG29tbVwzbB+SM7NPtJZrFbILWPCsAcULIggbHeA8FJtCW14pnJHGpDyW/iwhDkXQbBvjd/268JloJBn6S5w=
    # TWINE_PASSWORD
    - secure: Tcv7svUE6ptkVXWLyw4Dy/pyag6lIFODqij8A+DTRpfL2uvKouxy7tfjqSuLGa9QanulCDacNfrjLVqZtIEiUP1T702aMGySZY7Nfp67LdR731K4DrwwL/sX74Xwp8uftVdCEybJ6GLHJ9LkxpNAsszqkTAqsyL8fxvBuzwU1NvCLmIr2Qd+9ZL9m9Dns6Nz3HQki06K5aU8UCRGaDbWQ6Pl8qSldO3s4AnviJAQLVHKhyUE17qQY/8qTWudMfxnBkx5lTFj7Kafvn4aejICAi7phrtyp1Yo5zLXkE5WGDSRRjaWfW0/npP+EIRAmIhoc3Vu7jXONIFzkbLUCRIfGyX9Aetbu2p3a/Kw9pnNAg/42N7pC3cyMl1Vlx0eCxVBxsU/9JyLffqvjig6WEgn/qQjIzI7ZeJrqACpW0QXIKWzm0a0xG0W7mi1CjXtFZm5aH9C+K0F9f/dptBWXUop0lPnzRdGcMlcJX0/wB0zgYF7Q9FDKAdJ6fX+uNI8xKr76mhvhMcIVI6wzgnX1QKURRJAI6JXOiYUgHL6OzlsgsZ8u83ogqC0hu2v9Fi4Mc2DSrMmNHdQ3ETd3o6h76Bm4467APK748MKBD6IFM/0no0KsO+PkvjMNCyulkgg62kVkZ1tImAOEOKnjvYpIHDT0qNQUotG8jxT7IgJJbjEgoA=

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: test
      name: Integration Tests
      script: scripts/integration-tests.sh

    - name: Backend Unit Tests
      script: scripts/backend-unit-tests.sh

    - name: Frontend Unit Tests
      script: scripts/frontend-unit-tests.sh

    - name: Build Frontend
      script: scripts/build-frontend.sh

    - name: Test Publish Backend
      script: TWINE_PASSWORD=$TWINE_TEST_PASSWORD scripts/pypi-publish.sh --repository-url https://test.pypi.org/legacy/

    - name: Publish Backend
      if: tag =~ ^v
      script: scripts/pypi-publish.sh

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: WCOmV8D8ASU8IALFN6VNJ1pW3Bv2P8LZ2Sh5tXC+EbLloxb839X7j7Wih2cRAIBDEMdWdYByDDZD5Smoy6wEJQQBI6VmNbC+yBfNgpnfrITOYdq7mI8lH2AkmXxOsMPvTrBcbWE7ydSY0FHZ82+CuhIi+urwlECSscyzTo76iLVYdYi87hkqsx6OI3iL/METNFSSNd3ZZdr1+KBFvTYQx/4yFBKbj8rBlQgORF38gK7Q7h2sIC2Cp6inorY0JErhkuiVhVY4UWr/+tTfk+fjT6X5xiPkMDjXDNA3qz1UYqCDTJlcFy1oZsAYhblOXAhH+Az2mKynzMV5Q9YNj5pdIEoudGmxjzbyKW6/60ecOPh6ds+VIQr//XEkgZUWzxx+VOZKFZmddhWbMuBZcgf2L9ymq5kmIQHhgwvg2WDtkUDlUGe6ZC5MGbFPMPxU1+F6VEI5FzFsdlwxI+DMMVm5LpbnL6SwPSI7PT4edyKEfde7+MWYL7ZCR/bdYz9C8NOI0+XfDQpbuHeIrMZgizKvDqOzRhXPGBfCU1tyO3n24MlI1TljCXqoNaex0A480HeiXEYLjVOkl3CAQ1dzk5geuUxIe1ROz0so5bpqj5Ys1uX0YUMznt88t73Vw1i0/5PoVBnS0cRX3kjJFUoeyN6hlV5TKRke5g/RFHfpAfCejIM=
    file: webpi-frontend.tar.gz
    on:
      tags: true
      repo: urbas/webpi