# for more info on secret_key see https://flask.palletsprojects.com/en/1.1.x/api/?highlight=secret_key#flask.Flask.secret_key
secret_key: please-set-to something
users:
  foo@bar.com:
    # to generate salt-hashed passwords:
    #   python -c "from webpi import users; users.serialize_password('yourpassword')"
    password: ScejHHEWFdTPXb8c2/T5fwCw9tzXJ1iW3Pf6CjIrX/l7AmRd7JxovlbIGBicToQK2v0YXPGpzIS3iwS0R2/Q6A==
    salt: DM9X5i4muvNl9g==