version: 2.0
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Integration Tests
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            NODE_VERSION=$(cat .nvmrc) PYTHON_VERSION=$(cat .python-version) ~/docker-compose run itests npm run itests